# Generated by Django 4.1.2 on 2022-10-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.CharField(max_length=100)),
                ("contrasena", models.CharField(max_length=100)),
            ],
        ),
    ]
