# Generated by Django 4.1.2 on 2022-10-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="ingreso",
            field=models.BooleanField(default=False),
        ),
    ]
