# Generated by Django 4.1.2 on 2022-10-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categorie_ingreso"),
        ("users", "0001_initial"),
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="idcategoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.categorie"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="idusuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
